apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: rpdef-docker
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 443
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpdef-docker
spec:
  selector:
    matchLabels:
      app: rpdef-docker
  replicas: 5
  template:
    metadata:
      labels:
        app: rpdef-docker
    spec:
      containers:
      - name: rpdef-docker
        image: rpdef-docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443ls
        